name: Bug Report
description: Construct bug reports
body:
  - type: markdown
    attributes:
      value: You must use this template or your issue will be closed without investigation. Please see the guidelines.
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: Also tell us, what did you expect to happen?
      placeholder: Enter a concise description of your problem here
    validations:
      required: true
  - type: textarea
    id: attach
    attributes:
      label: Attach a .c3p
      description: "A minimal Construct project (.c3p) is required to be attached. Your issue will likely be closed without investigation if you don't provide one. Please see the guidelines"
      placeholder: add the file to a zip, or rename the .c3p extension to .zip, it can be attached to the GitHub issue. (GitHub will not accept a file ending in .c3p.)
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: "These steps are essential for us to be able to help you. Usually it is impossible to investigate reports unless they include steps we can follow ourselves, so please do your best to provide specific steps. There is no need to explain how you made the attached project - just explain what to do to with the project to observe the issue."
      value: |
        1.
        2.
        3.
      render: bash
    validations:
      required: true
  - type: textarea
    id: observed-result
    attributes:
      label: Observed result
      description: What do you see happen?
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What did you expect to happen instead?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: details
    attributes:
      label: System details
      description: Otherwise please go to Menu > About > Platform information and paste that information there instead.
      render: shell
